#!/usr/bin/env python3
"""Stage the frozen four-seed CUB BRiG-RLE K16 validation table."""

import argparse
import math
from pathlib import Path
from statistics import mean

from cbmjev.contracts import stable_hash
from cbmjev.io import file_hash, read_json


SEEDS = (60, 61, 62, 63)
FORMAT = "cbmjev-cub-brig-rle-k16-validation-gate-v1"
STATUS = "DEVELOPMENT_VALIDATION_NOT_TEST_OR_LATENCY_EVIDENCE"


def render_table(path: Path) -> str:
    report = read_json(path)
    unsigned = dict(report)
    if (unsigned.pop("report_hash", None) != stable_hash(unsigned)
            or report.get("format") != FORMAT
            or report.get("evidence_status") != STATUS
            or report.get("split") != "validation"
            or report.get("budget_groups") != 16
            or report.get("seeds") != list(SEEDS)
            or report.get("samples_per_seed") != 594
            or report.get("same_validation_images_reused_across_seeds") is not True
            or report.get("gate_pass") is not False):
        raise ValueError("unexpected or invalid frozen BRiG-RLE report")

    rows = report.get("per_seed", [])
    if len(rows) != len(SEEDS) or [r.get("seed") for r in rows] != list(SEEDS):
        raise ValueError("missing or reordered seed rows")
    fields = ("brig_accuracy", "static_accuracy", "accuracy_delta",
              "brig_macro_f1", "static_macro_f1", "macro_f1_delta")
    for row in rows:
        if row.get("samples") != 594 or any(
                not isinstance(row.get(field), (int, float))
                or not math.isfinite(row[field]) for field in fields):
            raise ValueError("invalid seed metrics")
        paired = row["paired_correctness"]
        if sum(paired.values()) != 594:
            raise ValueError("paired correctness counts do not sum to 594")
        if (not math.isclose(row["brig_accuracy"] - row["static_accuracy"],
                             row["accuracy_delta"], abs_tol=1e-12)
                or not math.isclose(row["brig_macro_f1"] - row["static_macro_f1"],
                                    row["macro_f1_delta"], abs_tol=1e-12)):
            raise ValueError("seed deltas do not match source metrics")
    if (not math.isclose(mean(r["accuracy_delta"] for r in rows),
                         report["mean_accuracy_delta"], abs_tol=1e-12)
            or not math.isclose(mean(r["macro_f1_delta"] for r in rows),
                                report["mean_macro_f1_delta"], abs_tol=1e-12)
            or report.get("positive_accuracy_seeds") != 0
            or report.get("positive_macro_f1_seeds") != 0):
        raise ValueError("summary disagrees with the four seed rows")

    lines = [
        "% Generated by scripts/figures/stage_cub_brig_rle_k16_gate_table.py",
        f"% Source: {path.as_posix()}; sha256={file_hash(path)}",
        "% Repeatedly inspected CUB validation, same 594 images per seed; not test or latency evidence.",
        "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lrrrrrr@{}}",
        "\\toprule",
        "Seed & BRiG Acc. & Static Acc. & $\\Delta$ Acc. & BRiG F1 & Static F1 & $\\Delta$ F1 \\\\ ",
        "\\midrule",
    ]
    for row in rows:
        values = [row[field] * 100 for field in fields]
        lines.append(f"{row['seed']} & " + " & ".join(f"{value:+.2f}" if i in (2, 5)
                                                   else f"{value:.2f}"
                                                   for i, value in enumerate(values)) + " \\\\ ")
    lines.append("\\midrule")
    averages = [mean(row[field] for row in rows) * 100 for field in fields]
    lines.append("Mean & " + " & ".join(f"{value:+.2f}" if i in (2, 5)
                                          else f"{value:.2f}"
                                          for i, value in enumerate(averages)) + " \\\\ ")
    lines += ["\\bottomrule", "\\end{tabular*}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=Path(
        "results/diagnostics/cub_brig_rle_k16_gate_60_63_v1.json"))
    parser.add_argument("--out", type=Path, default=Path(
        "paper/cvpr2027/generated/cub_brig_rle_k16_gate_table.tex"))
    args = parser.parse_args()
    content = render_table(args.report)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(args.out)


if __name__ == "__main__":
    main()
