#!/usr/bin/env python3
"""Stage a validation-only CUB K2 diagnostic table from four raw reports."""
import argparse
import hashlib
import json
from pathlib import Path


SEEDS = (60, 61, 62, 63)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reports", type=Path, default=Path("results/diagnostics"))
    parser.add_argument("--out", type=Path, default=Path(
        "paper/cvpr2027/generated/cub_oof_k2_validation_table.tex"))
    args = parser.parse_args()
    rows = []
    scripts = set()
    for seed in SEEDS:
        path = args.reports / f"cub_oof_conditional_second_query_seed{seed}_v2.json"
        raw = path.read_bytes()
        report = json.loads(raw)
        if (report["seed"] != seed or report["validation_rows"] != 594
                or report["training_rows"] != 4807
                or report["validation_labels_used_for_fit"] is not False
                or report["outer_fold_target_labels_used_for_fit"] is not True
                or report["evidence_status"]
                != "TRAIN_OOF_FIT_VALIDATION_EVALUATION_NOT_LOCKED_TEST"):
            raise ValueError(f"invalid K2 development report: {path}")
        scripts.add(report["analysis_script_sha256"])
        a = report["aggregate"]
        rows.append((seed, a["fixed_ce"], a["adaptive_ce"],
                     a["adaptive_minus_fixed_ce"],
                     100 * a["adaptive_minus_fixed_accuracy"],
                     hashlib.sha256(raw).hexdigest()))
    if len(scripts) != 1:
        raise ValueError("reports were not generated by one analysis script")
    lines = ["% Generated by scripts/figures/stage_cub_oof_k2_table.py",
             "% Validation diagnostic only; not a locked-test or JEV effect.",
             "\\begin{tabular}{@{}rrrrr@{}}",
             "\\toprule",
             "Seed & Fixed CE & Conditional CE & $\\Delta$ CE & $\\Delta$ Acc. (pp) \\\\",
             "\\midrule"]
    for seed, fixed, conditional, delta_ce, delta_acc, digest in rows:
        lines.append(f"% seed {seed} report sha256 {digest}")
        lines.append(f"{seed} & {fixed:.4f} & {conditional:.4f} & "
                     f"{delta_ce:+.4f} & {delta_acc:+.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(args.out)


if __name__ == "__main__":
    main()
