#!/usr/bin/env python3
"""Stage the label-clairvoyant CUB K16 last-query diagnostic table."""

import argparse
from pathlib import Path
from statistics import mean

from cbmjev.contracts import stable_hash
from cbmjev.io import file_hash, read_json


SEEDS = (60, 61, 62, 63)


def render_table(reports):
    if set(reports) != set(SEEDS):
        raise ValueError("exactly four declared seeds required")
    script_hashes = set()
    rows = []
    for seed in SEEDS:
        path = Path(reports[seed])
        report = read_json(path)
        unsigned = dict(report)
        if (unsigned.pop("report_hash", None) != stable_hash(unsigned)
                or report.get("seed") != seed
                or report.get("format") != "cbmjev-k16-last-query-hindsight-headroom-v1"
                or report.get("evidence_status") != "LABEL_CLAIRVOYANT_VALIDATION_DIAGNOSTIC_NOT_POLICY"
                or report.get("split") != "validation"
                or report.get("test_evaluated") is not False
                or report.get("summary", {}).get("samples") != 594
                or report["summary"].get("candidates") != 13):
            raise ValueError(f"invalid hindsight report: {path}")
        script_hashes.add(report["bindings"]["analysis_script_sha256"])
        metrics = report["summary"]
        if (metrics["label_clairvoyant_min_ce"] > metrics["fixed_ce"] + 1e-10
                or metrics["label_clairvoyant_ce_selected_accuracy"] >
                   metrics["label_clairvoyant_any_correct_accuracy"] + 1e-10):
            raise ValueError("hindsight ordering violated")
        rows.append((seed, metrics["fixed_accuracy"],
                     metrics["label_clairvoyant_ce_selected_accuracy"],
                     metrics["fixed_ce"], metrics["label_clairvoyant_min_ce"],
                     file_hash(path)))
    if len(script_hashes) != 1:
        raise ValueError("reports came from different analysis scripts")
    lines = ["% Generated by scripts/figures/stage_cub_k16_hindsight_table.py",
             "% True validation labels and unqueried answers select the final action.",
             "% NOT a deployable policy, Bayes bound, JEV result, or locked test.",
             "\\begin{tabular}{@{}rrrrr@{}}", "\\toprule",
             "Seed & Fixed Acc. & Hindsight Acc. & Fixed CE & Hindsight CE " + "\\\\",
             "\\midrule"]
    for seed, fixed_acc, hindsight_acc, fixed_ce, hindsight_ce, digest in rows:
        lines.append(f"% seed {seed} report sha256 {digest}")
        lines.append(f"{seed} & {100*fixed_acc:.2f} & {100*hindsight_acc:.2f} & "
                     f"{fixed_ce:.4f} & {hindsight_ce:.4f} " + "\\\\")
    lines += ["\\midrule",
              "Mean & " + " & ".join((
                  f"{100*mean(row[1] for row in rows):.2f}",
                  f"{100*mean(row[2] for row in rows):.2f}",
                  f"{mean(row[3] for row in rows):.4f}",
                  f"{mean(row[4] for row in rows):.4f}")) + " " + "\\\\",
              "\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reports", type=Path, default=Path("results/diagnostics"))
    parser.add_argument("--out", type=Path, default=Path(
        "paper/cvpr2027/generated/cub_k16_hindsight_table.tex"))
    args = parser.parse_args(argv)
    reports = {seed: args.reports / f"cub_k16_last_query_headroom_seed{seed}_v2.json"
               for seed in SEEDS}
    content = render_table(reports)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(args.out)


if __name__ == "__main__":
    main()
