"""Fast internal BRiG operations for states built from validated training rows.

These helpers deliberately do not replace public ``GroupQ.forward`` or
``Schema`` contracts. They may only be called by the fitter after
``training_rows`` has validated complete answers and after states have been
constructed by the private mask/reveal routines below.
"""

import torch
from torch.nn import functional as F

from cbmjev.brig import GroupQ, _terminal


class TrustedTrainingGroupQ(GroupQ):
    """GroupQ plus a validation-free forward for internally generated states."""

    def __init__(self, schema, hidden=128):
        super().__init__(schema, hidden)
        self._trusted_categories = tuple(schema.num_categories)
        offsets, cursor = [], 0
        for count in self._trusted_categories:
            offsets.append(cursor)
            cursor += count
        self._trusted_offsets = tuple(offsets)
        self._trusted_category_width = cursor
        self._trusted_group_atoms = tuple(group.atoms for group in schema.groups)

    def forward_trusted(self, observed_states, candidates, remaining_budget):
        """Score legal candidates for private states with prevalidated lineage."""
        if len(observed_states) != len(candidates) or not candidates:
            raise ValueError("nonempty aligned states/candidates required")
        if (type(remaining_budget) is not int
                or not 1 <= remaining_budget <= self.schema.num_groups):
            raise ValueError("invalid remaining budget")

        unique, lookup, inverse = [], {}, []
        for state in observed_states:
            key = tuple(state)
            index = lookup.get(key)
            if index is None:
                index = len(unique)
                lookup[key] = index
                unique.append(key)
            inverse.append(index)

        device = next(self.parameters()).device
        values = torch.tensor(unique, dtype=torch.long, device=device)
        observed = values >= 0
        safe = torch.where(observed, values, torch.zeros_like(values))
        categories = torch.zeros((len(unique), self._trusted_category_width),
                                 dtype=torch.float32, device=device)
        offsets = torch.tensor(self._trusted_offsets, dtype=torch.long, device=device)
        categories.scatter_(1, safe + offsets, observed.to(torch.float32))
        encoded = torch.cat((categories, observed.to(torch.float32)), dim=1)
        inverse_tensor = torch.tensor(inverse, dtype=torch.long, device=device)
        state_features = encoded.index_select(0, inverse_tensor)
        action_features = F.one_hot(
            torch.tensor(candidates, dtype=torch.long, device=device),
            self.schema.num_groups).to(torch.float32)
        budget_features = state_features.new_full(
            (len(candidates), 1), remaining_budget / self.schema.num_groups)
        return self.net(torch.cat(
            (state_features, action_features, budget_features), dim=1)).squeeze(-1)


def _available_groups_trusted(schema, state):
    return tuple(group for group, spec in enumerate(schema.groups)
                 if state[spec.atoms[0]] < 0)


def _reveal_trusted(schema, state, group, answers):
    """Reveal a legal group on an already-validated complete answer tuple."""
    revealed = list(state)
    for atom in schema.groups[group].atoms:
        revealed[atom] = answers[atom]
    return tuple(revealed)


@torch.no_grad()
def bellman_targets_trusted(head, schema, models, next_states, labels,
                            remaining_budget, device="cpu"):
    """Bellman targets over states/actions generated by this fitter only."""
    if not next_states or len(next_states) != len(labels) or remaining_budget < 1:
        raise ValueError("nonempty aligned Bellman examples required")
    if remaining_budget == 1:
        return _terminal(head, next_states, labels, device)
    previous = models[remaining_budget - 1]
    previous.eval()
    states, actions, lengths = [], [], []
    for state in next_states:
        candidates = _available_groups_trusted(schema, state)
        lengths.append(len(candidates))
        states.extend([state] * len(candidates))
        actions.extend(candidates)
    values = previous.forward_trusted(states, actions, remaining_budget - 1)
    return torch.stack([part.min() for part in values.split(lengths)]).to(device)


@torch.no_grad()
def empty_rollout_targets_trusted(schema, models, answers_batch, budget,
                                  *, max_candidate_evals=8192):
    """Generate exact BRiG empty-state trajectories without revalidating them."""
    if type(budget) is not int or not 2 <= budget <= schema.num_groups:
        raise ValueError("budget must be 2..num_groups")
    if type(max_candidate_evals) is not int or max_candidate_evals < schema.num_groups:
        raise ValueError("candidate-evaluation chunk must fit one complete action set")
    if not answers_batch:
        raise ValueError("nonempty answers_batch required")
    if any(left not in models for left in range(1, budget)):
        raise ValueError("missing previous-budget BRiG model")

    group_atoms = tuple(group.atoms for group in schema.groups)
    empty = schema.empty_state()
    answers, labels, first_actions, states = [], [], [], []
    for answer, label in answers_batch:
        for action, atoms in enumerate(group_atoms):
            state = list(empty)
            for atom in atoms:
                state[atom] = answer[atom]
            states.append(tuple(state))
            answers.append(answer)
            labels.append(label)
            first_actions.append(action)

    for left in range(budget - 1, 0, -1):
        previous = models[left]
        previous.eval()
        next_states = []
        cursor = 0
        while cursor < len(states):
            end, candidates = cursor, []
            while end < len(states):
                available = tuple(group for group, atoms in enumerate(group_atoms)
                                  if states[end][atoms[0]] < 0)
                if candidates and len(candidates) + len(available) > max_candidate_evals:
                    break
                candidates.extend((end, action) for action in available)
                end += 1
            values = previous.forward_trusted(
                [states[index] for index, _ in candidates],
                [action for _, action in candidates], left)
            if not torch.isfinite(values).all():
                raise ValueError("nonfinite BRiG rollout prediction")
            best = {}
            for (index, action), value in zip(candidates, values.tolist()):
                pair = (value, action)
                if index not in best or pair < best[index]:
                    best[index] = pair
            for index in range(cursor, end):
                next_states.append(_reveal_trusted(
                    schema, states[index], best[index][1], answers[index]))
            cursor = end
        states = next_states
    return [empty] * len(states), first_actions, states, labels


@torch.no_grad()
def precompute_empty_rollout_risks_trusted(schema, models, head, examples, budget,
                                           device="cpu", chunk_size=64):
    """Return exact ``[examples, groups]`` terminal-risk targets."""
    if not examples:
        raise ValueError("nonempty examples required")
    if type(chunk_size) is not int or chunk_size < 1:
        raise ValueError("positive integer chunk_size required")
    if type(budget) is not int or not 2 <= budget <= schema.num_groups:
        raise ValueError("cached empty rollout requires budget 2..num_groups")
    chunks = []
    for start in range(0, len(examples), chunk_size):
        batch = examples[start:start + chunk_size]
        _, _, terminal_states, terminal_labels = empty_rollout_targets_trusted(
            schema, models, batch, budget)
        risks = _terminal(head, terminal_states, terminal_labels, device)
        expected = len(batch) * schema.num_groups
        if risks.numel() != expected or not torch.isfinite(risks).all():
            raise ValueError("invalid empty-rollout risk target batch")
        chunks.append(risks.reshape(len(batch), schema.num_groups))
    return torch.cat(chunks, dim=0)


@torch.no_grad()
def precompute_empty_rollout_terminal_states_trusted(schema, models, examples,
                                                     budget, chunk_size=64):
    """Cache terminal states per example/action, preserving exact path order.

    Risks are deliberately not computed here: the fitter re-evaluates the
    cached states in the current shuffled minibatch order. This preserves the
    reference head's batch-dependent floating-point behavior while avoiding
    repeated lower-budget acquisition rollouts.
    """
    if not examples:
        raise ValueError("nonempty examples required")
    if type(chunk_size) is not int or chunk_size < 1:
        raise ValueError("positive integer chunk_size required")
    if type(budget) is not int or not 2 <= budget <= schema.num_groups:
        raise ValueError("terminal-state cache requires budget 2..num_groups")

    cached = []
    for start in range(0, len(examples), chunk_size):
        batch = examples[start:start + chunk_size]
        _, _, states, labels = empty_rollout_targets_trusted(
            schema, models, batch, budget)
        expected = len(batch) * schema.num_groups
        if len(states) != expected or len(labels) != expected:
            raise ValueError("invalid cached empty-rollout terminal states")
        for row, (_, label) in enumerate(batch):
            row_states = tuple(states[row * schema.num_groups:
                                      (row + 1) * schema.num_groups])
            row_labels = labels[row * schema.num_groups:
                                (row + 1) * schema.num_groups]
            if (len(row_states) != schema.num_groups
                    or row_labels != [label] * schema.num_groups):
                raise ValueError("terminal-state cache row/action alignment failed")
            cached.append(row_states)
    return tuple(cached)
