#!/usr/bin/env python3
"""Summarize development boundary/failure evidence for the CBMJev draft.

The output is deliberately labelled as development evidence.  It is meant to
keep negative results visible and prevent the paper from overclaiming when a
dataset only supports a boundary statement.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_metrics(path: Path) -> dict:
    metrics = json.loads(path.read_text(encoding="utf-8"))
    policies = metrics.get("policies", {})
    return {
        "path": str(path),
        "split": metrics.get("split"),
        "mode": metrics.get("mode"),
        "seed": metrics.get("seed"),
        "evidence_status": metrics.get("evidence_status"),
        "paper_evidence": metrics.get("paper_evidence"),
        "policies": policies,
    }


def pick(policy: dict, metric: str) -> float | None:
    value = policy.get(metric)
    return None if value is None else float(value)


def row(dataset: str, setting: str, metrics: dict, method: str, role: str) -> dict:
    policies = metrics["policies"]
    if method not in policies:
        raise ValueError(f"missing method {method} in {metrics['path']}")
    p = policies[method]
    return {
        "dataset": dataset,
        "setting": setting,
        "role": role,
        "method": method,
        "accuracy": pick(p, "accuracy"),
        "macro_f1": pick(p, "macro_f1"),
        "mean_queried_groups": pick(p, "mean_queried_groups"),
        "mean_calls": pick(p, "mean_calls"),
        "num_samples": int(p["num_samples"]),
        "source": metrics["path"],
        "evidence_status": metrics["evidence_status"],
    }


def fmt_pct(value: float | None) -> str:
    return "--" if value is None else f"{100.0 * value:.2f}"


def fmt_num(value: float | None) -> str:
    return "--" if value is None else f"{value:.2f}"


def write_latex(rows: list[dict], path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/summarize_boundary_evidence.py",
        "\\begin{tabular}{@{}lllrrrr@{}}",
        "\\toprule",
        "Dataset & Setting & Method & Groups & Calls & Acc. & Macro-F1\\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r['dataset']} & {r['setting']} & {r['role']} & "
            f"{fmt_num(r['mean_queried_groups'])} & {fmt_num(r['mean_calls'])} & "
            f"{fmt_pct(r['accuracy'])} & {fmt_pct(r['macro_f1'])}\\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_markdown(rows: list[dict], path: Path) -> None:
    lines = [
        "# CBMJev Boundary Evidence",
        "",
        "Development evidence only. These rows document where the current system",
        "does not yet support a positive algorithmic claim.",
        "",
        "| Dataset | Setting | Method | Groups | Calls | Acc. | Macro-F1 | Interpretation |",
        "|---|---|---|---:|---:|---:|---:|---|",
    ]
    for r in rows:
        interp = ""
        if r["dataset"] == "CEBaB" and r["role"] == "Dynamic value":
            interp = "Value policy saves concept groups but loses macro-F1 versus all concepts."
        elif r["setting"] == "balanced seed70" and r["role"] == "All concepts":
            interp = "All concepts improve balanced accuracy but induce many false positives."
        elif r["dataset"].startswith("ISIC") and r["role"] == "Dynamic value":
            interp = "Stops at the majority-class prior; not medical evidence."
        elif r["role"] == "All concepts":
            interp = "Reference with all automatic concepts."
        elif r["role"] == "No concepts":
            interp = "Prior/majority-style baseline."
        lines.append(
            f"| {r['dataset']} | {r['setting']} | {r['role']} | "
            f"{fmt_num(r['mean_queried_groups'])} | {fmt_num(r['mean_calls'])} | "
            f"{fmt_pct(r['accuracy'])} | {fmt_pct(r['macro_f1'])} | {interp} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cebab", required=True)
    parser.add_argument("--isic", required=True)
    parser.add_argument("--isic-balanced")
    parser.add_argument("--json-output", required=True)
    parser.add_argument("--latex-output", required=True)
    parser.add_argument("--markdown-output", required=True)
    args = parser.parse_args()

    cebAb = load_metrics(Path(args.cebab))
    isic = load_metrics(Path(args.isic))
    isic_balanced = load_metrics(Path(args.isic_balanced)) if args.isic_balanced else None
    rows = [
        row("CEBaB", "chaincheck", cebAb, "stop", "No concepts"),
        row("CEBaB", "chaincheck", cebAb, "all", "All concepts"),
        row("CEBaB", "chaincheck", cebAb, "value", "Dynamic value"),
        row("ISIC binary", "pilot", isic, "stop", "No concepts"),
        row("ISIC binary", "pilot", isic, "all", "All concepts"),
        row("ISIC binary", "pilot", isic, "value", "Dynamic value"),
    ]
    if isic_balanced is not None:
        rows.extend([
            row("ISIC binary", "balanced seed70", isic_balanced, "stop", "No concepts"),
            row("ISIC binary", "balanced seed70", isic_balanced, "all", "All concepts"),
            row("ISIC binary", "balanced seed70", isic_balanced, "value", "Dynamic value"),
        ])
    payload = {
        "evidence_status": "DEVELOPMENT_BOUNDARY_EVIDENCE_NOT_MAIN_POSITIVE_CLAIM",
        "rows": rows,
        "sources": {"cebab": cebAb, "isic": isic,
                    **({"isic_balanced": isic_balanced} if isic_balanced else {})},
    }
    Path(args.json_output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json_output).write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    write_latex(rows, Path(args.latex_output))
    write_markdown(rows, Path(args.markdown_output))


if __name__ == "__main__":
    main()
