#!/usr/bin/env python3
"""Summarize CBMJev live responder profile summaries for paper drafting.

Profile outputs are development timing evidence unless the run was performed
under an explicitly controlled final hardware protocol.  This script keeps that
status visible while producing compact tables for the cost-accounting section.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def _seed_from_path(path: Path) -> str:
    for part in path.parts:
        match = re.search(r"seed(\d+)", part)
        if match:
            return match.group(1)
        if "seed" in part:
            return part
    return path.parent.name


def _config_order(name: str) -> tuple[int, int | str]:
    if name == "all":
        return (0, 0)
    match = re.fullmatch(r"batch_(\d+)", name)
    if match:
        return (1, int(match.group(1)))
    return (2, name)


def _metric(config: dict, name: str, stat: str = "p50") -> float:
    return float(config["timings"][name][stat])


def load_rows(path: Path) -> list[dict]:
    summary = json.loads(path.read_text(encoding="utf-8"))
    if summary.get("format") != "cbmjev-live-validation-profile-v1":
        raise ValueError(f"not a live profile summary: {path}")
    rows = []
    seed = _seed_from_path(path)
    for name, cfg in sorted(summary["configurations"].items(),
                            key=lambda item: _config_order(item[0])):
        rows.append({
            "source": str(path),
            "seed": seed,
            "configuration": name,
            "n_cases": int(summary["n_cases"]),
            "repeats": int(summary["repeats"]),
            "device": summary["device"],
            "batch_independent": summary["batch_independent"],
            "full_vs_split_mismatches": int(summary["full_vs_split_mismatches"]),
            "total_p50_ms": _metric(cfg, "total_wall_ms", "p50"),
            "total_p95_ms": _metric(cfg, "total_wall_ms", "p95"),
            "response_p50_ms": _metric(cfg, "response_ms", "p50"),
            "first_call_p50_ms": _metric(cfg, "first_call_response_ms", "p50"),
            "evidence_status": summary["evidence_status"],
        })
    return rows


def fmt(value: float) -> str:
    return f"{value:.1f}"


def write_markdown(rows: list[dict], path: Path) -> None:
    lines = [
        "# Live Profile Development Evidence",
        "",
        "These timings are live validation profiles, not final paper speedup claims.",
        "",
        "| Seed/run | Config | Cases | Total p50 ms | Total p95 ms | Response p50 ms | First-call p50 ms | Batch consistent |",
        "|---|---|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['seed']} | {row['configuration']} | {row['n_cases']} | "
            f"{fmt(row['total_p50_ms'])} | {fmt(row['total_p95_ms'])} | "
            f"{fmt(row['response_p50_ms'])} | {fmt(row['first_call_p50_ms'])} | "
            f"{row['batch_independent']} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_latex(rows: list[dict], path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/summarize_live_profiles.py",
        "\\begin{tabular}{@{}llrrrrr@{}}",
        "\\toprule",
        "Run & Config & Cases & p50 & p95 & R p50 & First p50\\\\",
        "\\midrule",
    ]
    for row in rows:
        config = row["configuration"].replace("_", "\\_")
        lines.append(
            f"{row['seed']} & {config} & "
            f"{row['n_cases']} & {fmt(row['total_p50_ms'])} & "
            f"{fmt(row['total_p95_ms'])} & {fmt(row['response_p50_ms'])} & "
            f"{fmt(row['first_call_p50_ms'])}\\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", nargs="+", required=True)
    parser.add_argument("--json-output", required=True)
    parser.add_argument("--markdown-output", required=True)
    parser.add_argument("--latex-output", required=True)
    args = parser.parse_args()
    rows = []
    for item in args.inputs:
        rows.extend(load_rows(Path(item)))
    payload = {
        "evidence_status": "LIVE_PROFILE_DEVELOPMENT_NOT_PAPER_SPEEDUP_CLAIM",
        "rows": rows,
    }
    Path(args.json_output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json_output).write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    write_markdown(rows, Path(args.markdown_output))
    write_latex(rows, Path(args.latex_output))


if __name__ == "__main__":
    main()
